CREATE DATABASE SPMedicalGroup;

USE SPMedicalGroup;

CREATE TABLE TipoUsuario (
	IdTipoUsuario INT PRIMARY KEY IDENTITY,
	TituloTipo VARCHAR (255) NOT NULL UNIQUE
	);

CREATE TABLE Especialidade (
	IdEspecialidade INT PRIMARY KEY IDENTITY,
	TituloEsp VARCHAR (255) NOT NULL UNIQUE
	);

CREATE TABLE Situacao (
	IdSituacao INT PRIMARY KEY IDENTITY,
	TituloSituacao VARCHAR (255) NOT NULL UNIQUE
	);

CREATE TABLE Estado (
	IdEstado INT PRIMARY KEY IDENTITY,
	NomeEstado VARCHAR (255) NOT NULL UNIQUE
	);

CREATE TABLE Cidade (
	IdCidade INT PRIMARY KEY IDENTITY,
	NomeCidade VARCHAR (255) NOT NULL,
	IdEstado INT FOREIGN KEY REFERENCES Estado (IdEstado) NOT NULL
	);

CREATE TABLE Bairro (
	IdBairro INT PRIMARY KEY IDENTITY,
	NomeBairro VARCHAR(255) NOT NULL,
	IdCidade INT FOREIGN KEY REFERENCES Cidade (IdCidade) NOT NULL
	);

CREATE TABLE Logradouro (
	IdLogradouro INT PRIMARY KEY IDENTITY,
	NomeLogradouro VARCHAR(255) NOT NULL,
	IdBairro INT FOREIGN KEY REFERENCES Bairro (IdBairro) NOT NULL
	);

CREATE TABLE CEP (
	IdCep INT PRIMARY KEY IDENTITY,
	NumeroCep VARCHAR(255) NOT NULL UNIQUE,
	IdLogradouro INT FOREIGN KEY REFERENCES Logradouro (IdLogradouro) NOT NULL
	);

CREATE TABLE Endereco (
	IdEndereco INT PRIMARY KEY IDENTITY,
	Numero INT NOT NULL,
	IdCep INT FOREIGN KEY REFERENCES CEP (IdCep) NOT NULL
	);

CREATE TABLE Clinica (
	IdClinica INT PRIMARY KEY IDENTITY,
	NomeFantasia VARCHAR(255) NOT NULL,
	RazaoSocial VARCHAR(255) NOT NULL,
	CNPJ VARCHAR(255) NOT NULL,
	HorarioFuncionamento VARCHAR(255) NOT NULL,
	IdEndereco INT FOREIGN KEY REFERENCES Endereco (IdEndereco) NOT NULL
	);

CREATE TABLE Usuario (
	IdUsuario INT PRIMARY KEY IDENTITY,
	Email VARCHAR(255) NOT NULL UNIQUE,
	Senha VARCHAR(255) NOT NULL,
	IdTipoUsuario INT FOREIGN KEY REFERENCES TipoUsuario(IdTipoUsuario) NOT NULL,
	IdClinica INT FOREIGN KEY REFERENCES Clinica(IdClinica) NOT NULL
	);

CREATE TABLE Paciente (
	IdPaciente INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(255) NOT NULL,
	CPF VARCHAR(255) NOT NULL UNIQUE,
	RG VARCHAR(255) NOT NULL UNIQUE,
	DataNascimento DATE NOT NULL,
	Telefone VARCHAR(255) NOT NULL,
	IdUsuario INT FOREIGN KEY REFERENCES Usuario(IdUsuario) NOT NULL,
	IdEndereco INT FOREIGN KEY REFERENCES Endereco(IdEndereco) NOT NULL
	);

CREATE TABLE Medico (
	IdMedico INT PRIMARY KEY IDENTITY,
	NomeMedico VARCHAR(255) NOT NULL,
	CRM VARCHAR(255) NOT NULL UNIQUE,
	IdClinica INT FOREIGN KEY REFERENCES Clinica(IdClinica) NOT NULL,
	IdEspecialidade INT FOREIGN KEY REFERENCES Especialidade(IdEspecialidade) NOT NULL,
	IdUsuario INT FOREIGN KEY REFERENCES Usuario(IdUsuario) NOT NULL
	);

CREATE TABLE Consulta (
	IdConsulta INT PRIMARY KEY IDENTITY,
	DataConsulta DATETIME NOT NULL,
	Descricao VARCHAR(255),
	IdPaciente INT FOREIGN KEY REFERENCES Paciente(IdPaciente) NOT NULL,
	IdMedico INT FOREIGN KEY REFERENCES Medico(IdMedico) NOT NULL,
	IdSituacao INT FOREIGN KEY REFERENCES Situacao(IdSituacao) NOT NULL
	);